version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7
    container_name: task-manager-db
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - task-network

  # Backend API
  backend:
    build: ./backend
    container_name: task-manager-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/taskmanager
    depends_on:
      - mongo
    networks:
      - task-network

  # Frontend Web App
  frontend:
    build: ./frontend
    container_name: task-manager-web
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - task-network

volumes:
  mongo_data:

networks:
  task-network:
    driver: bridge